### PR TITLE
Updated annotation, fixed validation errors.

### PR DESCRIPTION
**Pull request by Fransie**
Updated annotation of main classes (section Plan).
Added prefix for dcterms, and changed it to dc.
Resolved turtle syntax errors.

I removed the skos:scopeNote entries because they did not add extra information. skos:definitions seem to suffice.

### CODE REVIEW

**Comment by eknutov** [comment]
pull this PR, there are more dcterms: properties that can easily be changed to dc:
overall we have align on dc: and dc:terms (as well as others) as i believe there are multiple usages throughout the files and we should/must be using only one to avoid confusion and breeding prefixes

**Comment by Fransie** [comment]
Oops. I created this pull request for just a single commit (the one dated november 8) but now it includes a second commit (the one dated november 9).
It seems I still have to figure out how to limit a pull request to one commit (or a selection of commits).

**Comment by BakkerJesse** [comment]
We have been using dc(terms):subject to link our ontology, with our skos vocabulary. Reusing it to replace thema, might harm the understandability of the model.

So, I'm still not entirely sure about dc:subject, here. Its semantics seems to be a good fit. But perhaps, we'd want to have our own definition, in Dutch. This, then linked to some Dutch legislations, if any.. 

I also think that our userbase will probably keep searching for the term 'thema'. With 'onderwerp' as the direct translation of subject, it could be confusing. 'onderwerp' and 'thema' are also not the same thing. So we need to show somewhere, we replaced 'thema' with dc:subject in order to avoid this confusion. Either in a UI or the model itself..

`ro:thema dc:rdfs:subPropertyOf dc:subject` could be a solution.

But given the fact that dc(terms):subject is used as the link between skos and the ontology, as well as the fact that it does not fully align with (at least my understand of) thema, I think we should just stick with `ro:thema a owl:DatatypeProperty`

**Comment by eknutov** [comment]
`dc:subject` is commonly used , i don't see any need to reinvent the wheel and come up with yet another definition of the same thing.
Note that you don't have to literrally translate and/or describe `subject` in Dutch. What matters here is the DC definition: `Definition: The topic of the resource.
Comment: Typically, the subject will be represented using keywords, key phrases, or classification codes. Recommended best practice is to use a controlled vocabulary.`
and this is what can be translated if needed.

**Pull request merged**
